name: Assign Topics to Repos

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  assign-topics:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants necessary permissions to modify repository contents

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Step 3: Install required dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Debugging the token
      - name: Debug Token
        run: echo "Token is set"
        env:
          MY_ACCESS_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}

      # Step 5: Run the Python script
      - name: Run assign topics script
        env:
          ACCESS_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
        run: python assign_topics.py
